# Generated by Django 3.1.4 on 2020-12-31 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naissance', models.FileField(upload_to=student.models.user_directory_path)),
                ('bac_premiere', models.FileField(upload_to=student.models.user_directory_path)),
                ('bac_deuxieme', models.FileField(upload_to=student.models.user_directory_path)),
                ('licence', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('master', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('doctorat', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('autre1', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('autre2', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info_personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('nationalite', models.CharField(max_length=250)),
                ('civilite', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=9)),
                ('phone', models.CharField(max_length=250)),
                ('date_naissance', models.DateField()),
                ('pays_naissance', models.CharField(max_length=250)),
                ('ville_naissance', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Baccalaureat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('serie_bac', models.CharField(choices=[('S-Scientifique', 'S-Scientifique'), ('S-Litteraire', 'S-Litteraire'), ('S-Technique', 'S-Technique')], max_length=15)),
                ('mention', models.CharField(choices=[('Tres Bien', 'Tres Bien'), ('Bien', 'Bien'), ('Assez Bien', 'Assez Bien'), ('Passable', 'Passable')], max_length=12)),
                ('pays_obtention', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
